# yarowa-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yarowa-web-app.fullname" . }}
  labels:
    {{- include "yarowa-web-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "yarowa-web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yarowa-web-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.appPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.appPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
