repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.11.1
    values:
      - ingress-nginx.yaml

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - prometheus-values.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml

  - name: yarowa-web-app
    chart: ../helmchart/yarowa-web-app
    namespace: production
    installed: true
    values:
      - web-app.yaml