appPort: 5000

image:
  repository: eduardmxyz/yarowa-web-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: casestudy.local.yarowa.io
      paths:
      - path: /
        pathType: Prefix
    - host:
      paths:
      - path: /
        pathType: Prefix
  tls: []