appPort: 5000

image:
  repository: eduardmxyz/yarowa-web-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: casestudy.local.yarowa.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host:
      paths:
      - path: /
        pathType: ImplementationSpecific
  tls: []